name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: isbang/compose-action@v1.0.0
      with:
        compose-file: './examples/docker-compose.yml'
        down-flags: '--volumes'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
